// Code generated by protoc-gen-go. DO NOT EDIT.
// source: place/place_service.proto

package place

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Latlong              string   `protobuf:"bytes,3,opt,name=latlong,proto3" json:"latlong,omitempty"`
	Radius               int32    `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Types                string   `protobuf:"bytes,5,opt,name=types,proto3" json:"types,omitempty"`
	Country              string   `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Key                  string   `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Request) GetLatlong() string {
	if m != nil {
		return m.Latlong
	}
	return ""
}

func (m *Request) GetRadius() int32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *Request) GetTypes() string {
	if m != nil {
		return m.Types
	}
	return ""
}

func (m *Request) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Request) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Response struct {
	HtmlAttributions     []string            `protobuf:"bytes,1,rep,name=html_attributions,json=htmlAttributions,proto3" json:"html_attributions,omitempty"`
	NextPageToken        string              `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Results              []*Response_RESULTS `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Status               string              `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHtmlAttributions() []string {
	if m != nil {
		return m.HtmlAttributions
	}
	return nil
}

func (m *Response) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *Response) GetResults() []*Response_RESULTS {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Response_RESULTS struct {
	Geometry             *Response_RESULTS_GEOMETRY  `protobuf:"bytes,1,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Icon                 string                      `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Id                   string                      `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Photos               []*Response_RESULTS_PHOTOS  `protobuf:"bytes,5,rep,name=photos,proto3" json:"photos,omitempty"`
	PlaceId              string                      `protobuf:"bytes,6,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	PlusCode             *Response_RESULTS_PLUS_CODE `protobuf:"bytes,7,opt,name=plus_code,json=plusCode,proto3" json:"plus_code,omitempty"`
	Rating               float64                     `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Reference            string                      `protobuf:"bytes,9,opt,name=reference,proto3" json:"reference,omitempty"`
	Scope                string                      `protobuf:"bytes,10,opt,name=scope,proto3" json:"scope,omitempty"`
	Types                []string                    `protobuf:"bytes,11,rep,name=types,proto3" json:"types,omitempty"`
	Vicinity             string                      `protobuf:"bytes,12,opt,name=vicinity,proto3" json:"vicinity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Response_RESULTS) Reset()         { *m = Response_RESULTS{} }
func (m *Response_RESULTS) String() string { return proto.CompactTextString(m) }
func (*Response_RESULTS) ProtoMessage()    {}
func (*Response_RESULTS) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0}
}
func (m *Response_RESULTS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS.Unmarshal(m, b)
}
func (m *Response_RESULTS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS.Merge(dst, src)
}
func (m *Response_RESULTS) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS.Size(m)
}
func (m *Response_RESULTS) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS proto.InternalMessageInfo

func (m *Response_RESULTS) GetGeometry() *Response_RESULTS_GEOMETRY {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Response_RESULTS) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Response_RESULTS) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response_RESULTS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response_RESULTS) GetPhotos() []*Response_RESULTS_PHOTOS {
	if m != nil {
		return m.Photos
	}
	return nil
}

func (m *Response_RESULTS) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *Response_RESULTS) GetPlusCode() *Response_RESULTS_PLUS_CODE {
	if m != nil {
		return m.PlusCode
	}
	return nil
}

func (m *Response_RESULTS) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Response_RESULTS) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Response_RESULTS) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Response_RESULTS) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Response_RESULTS) GetVicinity() string {
	if m != nil {
		return m.Vicinity
	}
	return ""
}

type Response_RESULTS_GEOMETRY struct {
	Location             *Response_RESULTS_GEOMETRY_LOCATION `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Viewport             *Response_RESULTS_GEOMETRY_VIEWPORT `protobuf:"bytes,2,opt,name=viewport,proto3" json:"viewport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Response_RESULTS_GEOMETRY) Reset()         { *m = Response_RESULTS_GEOMETRY{} }
func (m *Response_RESULTS_GEOMETRY) String() string { return proto.CompactTextString(m) }
func (*Response_RESULTS_GEOMETRY) ProtoMessage()    {}
func (*Response_RESULTS_GEOMETRY) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0, 0}
}
func (m *Response_RESULTS_GEOMETRY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY.Unmarshal(m, b)
}
func (m *Response_RESULTS_GEOMETRY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS_GEOMETRY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS_GEOMETRY.Merge(dst, src)
}
func (m *Response_RESULTS_GEOMETRY) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY.Size(m)
}
func (m *Response_RESULTS_GEOMETRY) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS_GEOMETRY.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS_GEOMETRY proto.InternalMessageInfo

func (m *Response_RESULTS_GEOMETRY) GetLocation() *Response_RESULTS_GEOMETRY_LOCATION {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Response_RESULTS_GEOMETRY) GetViewport() *Response_RESULTS_GEOMETRY_VIEWPORT {
	if m != nil {
		return m.Viewport
	}
	return nil
}

type Response_RESULTS_GEOMETRY_LOCATION struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_RESULTS_GEOMETRY_LOCATION) Reset()         { *m = Response_RESULTS_GEOMETRY_LOCATION{} }
func (m *Response_RESULTS_GEOMETRY_LOCATION) String() string { return proto.CompactTextString(m) }
func (*Response_RESULTS_GEOMETRY_LOCATION) ProtoMessage()    {}
func (*Response_RESULTS_GEOMETRY_LOCATION) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0, 0, 0}
}
func (m *Response_RESULTS_GEOMETRY_LOCATION) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_LOCATION.Unmarshal(m, b)
}
func (m *Response_RESULTS_GEOMETRY_LOCATION) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_LOCATION.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS_GEOMETRY_LOCATION) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_LOCATION.Merge(dst, src)
}
func (m *Response_RESULTS_GEOMETRY_LOCATION) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_LOCATION.Size(m)
}
func (m *Response_RESULTS_GEOMETRY_LOCATION) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_LOCATION.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS_GEOMETRY_LOCATION proto.InternalMessageInfo

func (m *Response_RESULTS_GEOMETRY_LOCATION) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Response_RESULTS_GEOMETRY_LOCATION) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Response_RESULTS_GEOMETRY_VIEWPORT struct {
	Northeast            *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST `protobuf:"bytes,1,opt,name=northeast,proto3" json:"northeast,omitempty"`
	Southwest            *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST `protobuf:"bytes,2,opt,name=southwest,proto3" json:"southwest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *Response_RESULTS_GEOMETRY_VIEWPORT) Reset()         { *m = Response_RESULTS_GEOMETRY_VIEWPORT{} }
func (m *Response_RESULTS_GEOMETRY_VIEWPORT) String() string { return proto.CompactTextString(m) }
func (*Response_RESULTS_GEOMETRY_VIEWPORT) ProtoMessage()    {}
func (*Response_RESULTS_GEOMETRY_VIEWPORT) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0, 0, 1}
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT.Unmarshal(m, b)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS_GEOMETRY_VIEWPORT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT.Merge(dst, src)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT.Size(m)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT proto.InternalMessageInfo

func (m *Response_RESULTS_GEOMETRY_VIEWPORT) GetNortheast() *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST {
	if m != nil {
		return m.Northeast
	}
	return nil
}

func (m *Response_RESULTS_GEOMETRY_VIEWPORT) GetSouthwest() *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST {
	if m != nil {
		return m.Southwest
	}
	return nil
}

type Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) Reset() {
	*m = Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST{}
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) String() string {
	return proto.CompactTextString(m)
}
func (*Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) ProtoMessage() {}
func (*Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0, 0, 1, 0}
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST.Unmarshal(m, b)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST.Merge(dst, src)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST.Size(m)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST proto.InternalMessageInfo

func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) Reset() {
	*m = Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST{}
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) String() string {
	return proto.CompactTextString(m)
}
func (*Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) ProtoMessage() {}
func (*Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0, 0, 1, 1}
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST.Unmarshal(m, b)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST.Merge(dst, src)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST.Size(m)
}
func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST proto.InternalMessageInfo

func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Response_RESULTS_PHOTOS struct {
	Height               float64  `protobuf:"fixed64,1,opt,name=height,proto3" json:"height,omitempty"`
	HtmlAttributions     []string `protobuf:"bytes,2,rep,name=html_attributions,json=htmlAttributions,proto3" json:"html_attributions,omitempty"`
	PhotoReference       string   `protobuf:"bytes,3,opt,name=photo_reference,json=photoReference,proto3" json:"photo_reference,omitempty"`
	Width                float64  `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_RESULTS_PHOTOS) Reset()         { *m = Response_RESULTS_PHOTOS{} }
func (m *Response_RESULTS_PHOTOS) String() string { return proto.CompactTextString(m) }
func (*Response_RESULTS_PHOTOS) ProtoMessage()    {}
func (*Response_RESULTS_PHOTOS) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0, 1}
}
func (m *Response_RESULTS_PHOTOS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS_PHOTOS.Unmarshal(m, b)
}
func (m *Response_RESULTS_PHOTOS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS_PHOTOS.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS_PHOTOS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS_PHOTOS.Merge(dst, src)
}
func (m *Response_RESULTS_PHOTOS) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS_PHOTOS.Size(m)
}
func (m *Response_RESULTS_PHOTOS) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS_PHOTOS.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS_PHOTOS proto.InternalMessageInfo

func (m *Response_RESULTS_PHOTOS) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Response_RESULTS_PHOTOS) GetHtmlAttributions() []string {
	if m != nil {
		return m.HtmlAttributions
	}
	return nil
}

func (m *Response_RESULTS_PHOTOS) GetPhotoReference() string {
	if m != nil {
		return m.PhotoReference
	}
	return ""
}

func (m *Response_RESULTS_PHOTOS) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

type Response_RESULTS_PLUS_CODE struct {
	CompoundCode         string   `protobuf:"bytes,1,opt,name=compound_code,json=compoundCode,proto3" json:"compound_code,omitempty"`
	GlobalCode           string   `protobuf:"bytes,2,opt,name=global_code,json=globalCode,proto3" json:"global_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_RESULTS_PLUS_CODE) Reset()         { *m = Response_RESULTS_PLUS_CODE{} }
func (m *Response_RESULTS_PLUS_CODE) String() string { return proto.CompactTextString(m) }
func (*Response_RESULTS_PLUS_CODE) ProtoMessage()    {}
func (*Response_RESULTS_PLUS_CODE) Descriptor() ([]byte, []int) {
	return fileDescriptor_place_service_8a72e694c23c5fe9, []int{1, 0, 2}
}
func (m *Response_RESULTS_PLUS_CODE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RESULTS_PLUS_CODE.Unmarshal(m, b)
}
func (m *Response_RESULTS_PLUS_CODE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RESULTS_PLUS_CODE.Marshal(b, m, deterministic)
}
func (dst *Response_RESULTS_PLUS_CODE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RESULTS_PLUS_CODE.Merge(dst, src)
}
func (m *Response_RESULTS_PLUS_CODE) XXX_Size() int {
	return xxx_messageInfo_Response_RESULTS_PLUS_CODE.Size(m)
}
func (m *Response_RESULTS_PLUS_CODE) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RESULTS_PLUS_CODE.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RESULTS_PLUS_CODE proto.InternalMessageInfo

func (m *Response_RESULTS_PLUS_CODE) GetCompoundCode() string {
	if m != nil {
		return m.CompoundCode
	}
	return ""
}

func (m *Response_RESULTS_PLUS_CODE) GetGlobalCode() string {
	if m != nil {
		return m.GlobalCode
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "place.Request")
	proto.RegisterType((*Response)(nil), "place.Response")
	proto.RegisterType((*Response_RESULTS)(nil), "place.Response.RESULTS")
	proto.RegisterType((*Response_RESULTS_GEOMETRY)(nil), "place.Response.RESULTS.GEOMETRY")
	proto.RegisterType((*Response_RESULTS_GEOMETRY_LOCATION)(nil), "place.Response.RESULTS.GEOMETRY.LOCATION")
	proto.RegisterType((*Response_RESULTS_GEOMETRY_VIEWPORT)(nil), "place.Response.RESULTS.GEOMETRY.VIEWPORT")
	proto.RegisterType((*Response_RESULTS_GEOMETRY_VIEWPORT_NORTHEAST)(nil), "place.Response.RESULTS.GEOMETRY.VIEWPORT.NORTHEAST")
	proto.RegisterType((*Response_RESULTS_GEOMETRY_VIEWPORT_SOUTHWEST)(nil), "place.Response.RESULTS.GEOMETRY.VIEWPORT.SOUTHWEST")
	proto.RegisterType((*Response_RESULTS_PHOTOS)(nil), "place.Response.RESULTS.PHOTOS")
	proto.RegisterType((*Response_RESULTS_PLUS_CODE)(nil), "place.Response.RESULTS.PLUS_CODE")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaceServiceClient is the client API for PlaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaceServiceClient interface {
	NearbySearchByTypes(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type placeServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlaceServiceClient(cc *grpc.ClientConn) PlaceServiceClient {
	return &placeServiceClient{cc}
}

func (c *placeServiceClient) NearbySearchByTypes(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/place.PlaceService/NearbySearchByTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceServiceServer is the server API for PlaceService service.
type PlaceServiceServer interface {
	NearbySearchByTypes(context.Context, *Request) (*Response, error)
}

func RegisterPlaceServiceServer(s *grpc.Server, srv PlaceServiceServer) {
	s.RegisterService(&_PlaceService_serviceDesc, srv)
}

func _PlaceService_NearbySearchByTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceServer).NearbySearchByTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceService/NearbySearchByTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceServer).NearbySearchByTypes(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "place.PlaceService",
	HandlerType: (*PlaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NearbySearchByTypes",
			Handler:    _PlaceService_NearbySearchByTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "place/place_service.proto",
}

func init() {
	proto.RegisterFile("place/place_service.proto", fileDescriptor_place_service_8a72e694c23c5fe9)
}

var fileDescriptor_place_service_8a72e694c23c5fe9 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x96, 0x93, 0x4d, 0x62, 0xbf, 0x74, 0xdb, 0x32, 0x20, 0xf0, 0x5a, 0x2b, 0x08, 0x45, 0x82,
	0x20, 0x24, 0x47, 0x9b, 0x95, 0x38, 0x21, 0xa4, 0x52, 0x2c, 0x5a, 0xa9, 0xd4, 0xd9, 0xb1, 0x4b,
	0xc5, 0x29, 0x4c, 0xec, 0xc1, 0x1e, 0xd5, 0x99, 0x31, 0xf6, 0x38, 0x25, 0x57, 0xce, 0x5c, 0x80,
	0xff, 0x0c, 0xce, 0xdc, 0xf8, 0x3f, 0x40, 0x33, 0xfe, 0x91, 0x0a, 0x11, 0x91, 0xbd, 0x44, 0xf3,
	0x7d, 0x79, 0xef, 0x9b, 0x79, 0xf3, 0xbe, 0x37, 0x86, 0x67, 0x79, 0x46, 0x22, 0x3a, 0xd3, 0xbf,
	0xcb, 0x92, 0x16, 0x1b, 0x16, 0x51, 0x37, 0x2f, 0x84, 0x14, 0x68, 0xa0, 0x49, 0xe7, 0x79, 0x22,
	0x44, 0x92, 0xd1, 0x19, 0xc9, 0xd9, 0x8c, 0x70, 0x2e, 0x24, 0x91, 0x4c, 0xf0, 0xb2, 0x0e, 0x3a,
	0xfb, 0xc5, 0x80, 0x11, 0xa6, 0x3f, 0x54, 0xb4, 0x94, 0x08, 0xc1, 0x93, 0x88, 0xc9, 0xad, 0xdd,
	0x9b, 0x18, 0x53, 0x0b, 0xeb, 0x35, 0xb2, 0x61, 0x94, 0x11, 0x99, 0x09, 0x9e, 0xd8, 0x7d, 0x4d,
	0xb7, 0x10, 0xbd, 0x0d, 0xc3, 0x82, 0xc4, 0xac, 0x2a, 0xed, 0x27, 0x13, 0x63, 0x3a, 0xc0, 0x0d,
	0x42, 0x6f, 0xc1, 0x40, 0x6e, 0x73, 0x5a, 0xda, 0x03, 0x1d, 0x5f, 0x03, 0xa5, 0x13, 0x89, 0x8a,
	0xcb, 0x62, 0x6b, 0x0f, 0x6b, 0x9d, 0x06, 0xa2, 0x53, 0xe8, 0xdf, 0xd3, 0xad, 0x3d, 0xd2, 0xac,
	0x5a, 0x9e, 0xfd, 0x6d, 0x81, 0x89, 0x69, 0x99, 0x0b, 0x5e, 0x52, 0xf4, 0x09, 0xbc, 0x91, 0xca,
	0x75, 0xb6, 0x24, 0x52, 0x16, 0x6c, 0x55, 0xe9, 0xb3, 0xdb, 0xc6, 0xa4, 0x3f, 0xb5, 0xf0, 0xa9,
	0xfa, 0xe3, 0xfc, 0x11, 0x8f, 0x3e, 0x84, 0x13, 0x4e, 0x7f, 0x94, 0xcb, 0x9c, 0x24, 0x74, 0x29,
	0xc5, 0x3d, 0xe5, 0x4d, 0x31, 0x4f, 0x15, 0xbd, 0x20, 0x09, 0x0d, 0x15, 0x89, 0x5e, 0xc0, 0xa8,
	0xa0, 0x65, 0x95, 0xc9, 0xd2, 0xee, 0x4f, 0xfa, 0xd3, 0xf1, 0xfc, 0x1d, 0x57, 0x5f, 0x96, 0xdb,
	0x6e, 0xeb, 0x62, 0x2f, 0xb8, 0xbd, 0x0e, 0x03, 0xdc, 0xc6, 0xa9, 0x72, 0x4b, 0x49, 0x64, 0x53,
	0xae, 0x85, 0x1b, 0xe4, 0xfc, 0x6e, 0xc2, 0xa8, 0x09, 0x46, 0x9f, 0x81, 0x99, 0x50, 0xb1, 0xa6,
	0xaa, 0x4a, 0x63, 0x62, 0x4c, 0xc7, 0xf3, 0xc9, 0x1e, 0x5d, 0xf7, 0x2b, 0xcf, 0xff, 0xda, 0x0b,
	0xf1, 0xb7, 0xb8, 0xcb, 0x50, 0xd7, 0xcf, 0x22, 0xd1, 0x9e, 0x58, 0xaf, 0xd1, 0x31, 0xf4, 0x58,
	0xdc, 0xdc, 0x7c, 0x8f, 0xc5, 0x2a, 0x86, 0x93, 0x35, 0x6d, 0xce, 0xa0, 0xd7, 0xe8, 0x53, 0x18,
	0xe6, 0xa9, 0x90, 0x42, 0xdd, 0xb8, 0xaa, 0xe5, 0xdd, 0x7d, 0x7b, 0x2e, 0x2e, 0xfd, 0xd0, 0x0f,
	0x70, 0x13, 0x8d, 0x9e, 0x81, 0x59, 0xdb, 0x86, 0xc5, 0x6d, 0x4f, 0x34, 0xbe, 0x8a, 0xd1, 0xe7,
	0x60, 0xe5, 0x59, 0x55, 0x2e, 0x23, 0x11, 0x53, 0xdd, 0x99, 0xf1, 0xfc, 0xfd, 0xbd, 0xaa, 0xd7,
	0xb7, 0xc1, 0xf2, 0xc2, 0xff, 0xd2, 0xc3, 0xa6, 0xca, 0xb9, 0x10, 0x31, 0xad, 0xbd, 0x21, 0x19,
	0x4f, 0x6c, 0x73, 0x62, 0x4c, 0x0d, 0xdc, 0x20, 0xf4, 0x1c, 0xac, 0x82, 0x7e, 0x4f, 0x0b, 0xca,
	0x23, 0x6a, 0x5b, 0x7a, 0xcf, 0x1d, 0xa1, 0x9c, 0x53, 0x46, 0x22, 0xa7, 0x36, 0xd4, 0xce, 0xd1,
	0x60, 0xe7, 0xa7, 0xb1, 0x6e, 0x7a, 0xe3, 0x27, 0x07, 0xcc, 0x0d, 0x8b, 0x18, 0x57, 0x7e, 0x3d,
	0xd2, 0xe1, 0x1d, 0x76, 0xfe, 0xec, 0x83, 0xd9, 0xde, 0x2f, 0xf2, 0xc0, 0xcc, 0x44, 0xa4, 0x3d,
	0xdf, 0xf4, 0xe4, 0xe3, 0xff, 0xeb, 0x89, 0x7b, 0xed, 0x5f, 0x9c, 0x87, 0x57, 0xfe, 0x0d, 0xee,
	0x52, 0x95, 0xcc, 0x86, 0xd1, 0x87, 0x5c, 0x14, 0x52, 0x37, 0xe8, 0x10, 0x99, 0x6f, 0xae, 0xbc,
	0xbb, 0x85, 0x8f, 0x43, 0xdc, 0xa5, 0x3a, 0x2e, 0x98, 0xad, 0xb8, 0x32, 0x7e, 0x46, 0xa4, 0x3e,
	0x94, 0x81, 0xd5, 0x52, 0x33, 0x3c, 0xd1, 0xfa, 0x8a, 0xe1, 0x89, 0xf3, 0x6b, 0x0f, 0xcc, 0x56,
	0x06, 0xbd, 0x02, 0x8b, 0x8b, 0x42, 0xa6, 0x94, 0x94, 0xb2, 0xa9, 0xe5, 0xe5, 0xc1, 0x87, 0x70,
	0x6f, 0x7c, 0x1c, 0x5e, 0x7a, 0xe7, 0x41, 0x88, 0x77, 0x2a, 0x4a, 0xb2, 0x14, 0x95, 0x4c, 0x1f,
	0x68, 0xd9, 0xd6, 0xf5, 0x1a, 0x92, 0x81, 0x7f, 0x1b, 0x5e, 0xde, 0x79, 0x4a, 0xb2, 0x53, 0x71,
	0x66, 0x60, 0x75, 0x5b, 0x1d, 0x54, 0xe3, 0x0c, 0xac, 0x4e, 0xe8, 0xa0, 0x84, 0x9f, 0x0d, 0x18,
	0xd6, 0x5e, 0x56, 0x46, 0x4b, 0x29, 0x4b, 0xd2, 0x36, 0xa3, 0x41, 0xff, 0xfd, 0x6a, 0xf4, 0xf6,
	0xbc, 0x1a, 0x1f, 0xc1, 0x89, 0x1e, 0x89, 0xe5, 0xce, 0x9b, 0xf5, 0xc4, 0x1d, 0x6b, 0x1a, 0x3f,
	0x36, 0xe8, 0x03, 0x8b, 0x65, 0xaa, 0xc7, 0xcf, 0xc0, 0x35, 0x70, 0x5e, 0x81, 0xd5, 0xcd, 0x00,
	0xfa, 0x00, 0x9e, 0x46, 0x62, 0x9d, 0x8b, 0x8a, 0xc7, 0xf5, 0xf4, 0x18, 0x5a, 0xe9, 0xa8, 0x25,
	0xf5, 0x78, 0xbc, 0x07, 0xe3, 0x24, 0x13, 0x2b, 0x92, 0xd5, 0x21, 0xf5, 0xc0, 0x43, 0x4d, 0xa9,
	0x80, 0xf9, 0x77, 0x70, 0xb4, 0x50, 0x4d, 0x08, 0xea, 0x07, 0x1d, 0x2d, 0xe0, 0xcd, 0x1b, 0x4a,
	0x8a, 0xd5, 0x36, 0xa0, 0xa4, 0x88, 0xd2, 0x2f, 0xb6, 0xa1, 0x1e, 0x82, 0xe3, 0xae, 0x55, 0xfa,
	0x01, 0x77, 0x4e, 0xfe, 0xd5, 0xba, 0x33, 0xfb, 0xa7, 0x3f, 0xfe, 0xfa, 0xad, 0x87, 0xd0, 0xe9,
	0x6c, 0xf3, 0xa2, 0xfe, 0x46, 0xcc, 0xb8, 0xd6, 0x59, 0x0d, 0xf5, 0xf3, 0xff, 0xf2, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0x8d, 0x3d, 0x3e, 0x40, 0x06, 0x00, 0x00,
}
